spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    username:
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      use-new-id-generator-mappings: false    # true 이면, Sequence Generator. 지원하지 않으면, Table Generator. false 이면 Native Generator.
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true

  h2:
    console:
      enabled: true
      path: /h2

  jwt:
    secret:
    blacklist:
      access-token: BlackListAccessToken

  redis:
    host:
    port:

  korea-tour-api:
    auth-key:
    url: http://apis.data.go.kr/B551011/KorService/

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.security: debug       # 1 day